name: Run PS Script

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  evaluate:
    name: Run check.ps1
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: ./check.ps1
        shell: pwsh
      - uses: gautamkrishnar/keepalive-workflow@v1
